
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/transactions
    password: '123456'
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: '8080'